alias k='kubectl'
alias kg='kubectl get'
alias ka='kubectl apply -f'
alias kc='kubectl create'
alias ke='kubectl edit'
alias kdel='kubectl delete'
alias ksns='kubectl config set-context $(k config current-context) --namespace'
alias kgns='kubectl config get-contexts'
alias krp='kubectl run --restart=Never --dry-run=client -o yaml --image'
alias kcj='kubectl job'
alias kcd='kubectl create deploy --dry-run=client -o yaml --image'
alias kcj='kubectl create job --dry-run=client -o yaml --image'
alias kcc='kubectl create cronjob --dry-run=client -o yaml --image'
alias ktemp='kubectl run busybox --image busybox --rm -it -- sh'
alias kd='kubectl describe'
alias k='kubectl'
alias k='kubectl'
